version: "3.0"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutku
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: productdb
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"